name: Upload to HAR

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install harness CLI
        run: curl -fsSL https://raw.githubusercontent.com/harness/harness-cli/v2/install | sh

      - name: Upload to HAR
        uses: sameeksha-harness/upload-to-har@main
        with:
          api-url: https://prod1.harness.io
          account: ${{ secrets.HARNESS_ACCOUNT_ID }}
          token: ${{ secrets.HARNESS_PAT_TOKEN }}
          registry: gotest
          type: go
          file: .
          name: my-module
          version: v0.0.1
